config/urls.py
from django.contrib import admin
from django.urls import path, include
from guild import views

urlpatterns = [
    path('guild/', include('guild.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

guild/urls.py
from django.urls import path

from . import views

app_name = 'guild'

urlpatterns = [
    path('', views.index, name='index'),
    path('chart/', views.chart, name='chart'),
    path('<str:character_name>/', views.history, name='history')
]

guild/models.py
from django.db import models
import re
from datetime import datetime, timedelta


class Member(models.Model):
    character_name = models.CharField(max_length=12, primary_key=True)  #캐릭터명
    character_class = models.CharField(max_length=6)
    character_item_level = models.FloatField()
    character_battle_level = models.IntegerField()
    character_expedition_level = models.IntegerField()
    character_engraving = models.CharField(max_length=200)
    character_stat = models.CharField(max_length=200)
    character_card = models.CharField(max_length=50)
    character_gem = models.CharField(max_length=200)
    character_equipment_level = models.CharField(max_length=200)
    character_power = models.IntegerField()
    character_vitality = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True, editable=True)
    modified_date = models.DateTimeField(auto_now=True, editable=True)

    def stat_as_list(self):
        return [stat for stat in self.character_stat.split(',') if stat[:2] in ['치명', '특화', '신속']]

    def equipment_weapon_lv(self):
        return re.sub(r'[^0-9]', '', self.character_equipment_level.split(',')[0])

    def equipment_as_list(self):
        return self.character_equipment_level.split(',')

    def engraving_simple(self):
        return re.sub(r'[^0-9]', '', self.character_engraving)

    def engraving_as_list(self):
        return self.character_engraving.split(',')

    def card_slice(self):
        return self.character_card.replace(')', '').split(' (')

    def gem_simple(self):
        if not self.character_gem: return
        gem_list = self.character_gem.split(',')
        counter = {}
        for gem in gem_list:
            gem = gem.replace('의 보석', '')
            if gem in counter:
                counter[gem] += 1
            else:
                counter[gem] = 1
        return [f'{key} x{value}' for key, value in counter.items()]

    @property
    def elapsed_time(self):
        time = datetime.now() - self.modified_date
        if time < timedelta(days=1):
            return '오늘'
        elif time < timedelta(days=7):
            return f'{datetime.now().day - self.modified_date.day}일전'
        else:
            return f'{self.modified_date.month}.{self.modified_date.day}'

    def __str__(self):
        return self.character_name


class History(models.Model):
    character_name = models.ForeignKey(Member, on_delete=models.CASCADE)
    field = models.CharField(max_length=50)
    before_data = models.CharField(max_length=200)
    after_data = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def field_trans(self):
        if self.field == 'character_item_level': return '아이템레벨'
        elif self.field == 'character_battle_level': return '전투레벨'
        elif self.field == 'character_expedition_level': return '원정대레벨'
        elif self.field == 'character_engraving': return '각인'
        elif self.field == 'character_stat': return '특성'
        elif self.field == 'character_card': return '카드'
        elif self.field == 'character_gem': return '보석'
        elif self.field == 'character_equipment_level': return '장비'
        elif self.field == 'character_power': return '공격력'
        elif self.field == 'character_vitality': return '생명력'

guild/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from .models import Member
from .models import History


def index(request):
    # character_list = Member.objects.order_by('-character_item_level')
    # character_list = Member.objects.extra(select={'character_item_level_int': 'CAST(character_item_level AS INTEGER)'}).order_by('-character_item_level_int')
    context = {}
    return render(request, 'guild/index.html', context)


def chart(request):
    character_list = Member.objects.order_by('-character_item_level')
    character_history = {}
    for character in character_list:
        character_name = character.character_name
        last_update = character.modified_date.date()
        character_history[character_name] = History.objects.filter(character_name=character_name, date__gte=last_update)
    context = {'character_list': character_list, 'character_history': character_history}
    return render(request, 'guild/character_list.html', context)


def history(request, character_name):
    character_history = History.objects.filter(character_name=character_name).order_by('-date')
    context = {'character_name': character_name, 'character_history': character_history}
    return render(request, 'guild/character_history.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!--    <meta name="description" content="">-->
<!--    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">-->
<!--    <meta name="generator" content="Hugo 0.101.0">-->

    <title>Day</title>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

</head>



<body>
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'guild:index' %}">Day</a>
<!--      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
<!--          <li class="nav-item">-->
<!--            <a class="nav-link active" aria-current="page" href="{% url 'guild:index' %}">chart</a>-->
<!--          </li>-->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'guild:chart' %}">chart</a>
          </li>
<!--          <li class="nav-item">-->
<!--            <a class="nav-link disabled">Disabled</a>-->
<!--          </li>-->
        </ul>
<!--        <form class="d-flex" role="search">-->
<!--          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--          <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--        </form>-->
      </div>
    </div>
  </nav>
</header>


<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
      {% block content %}
      {% endblock %}
    <h1 class="mt-5">Sticky footer with fixed navbar</h1>
    <p class="lead">Pin a footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code class="small">padding-top: 60px;</code> on the <code class="small">main &gt; .container</code>.</p>
    <p>Back to <a href="../examples/sticky-footer/">the default sticky footer</a> minus the navbar.</p>
  </div>
</main>


<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>


<script src="{% static 'bootstrap.min.js' %}"></script>


</body>
</html>

templates/guild/character_history.html
{% extends 'base.html' %}
{% load guild_filter %}
{% block content %}


<h1>{{character_name}}</h1>
<div class="table-responsive text-nowrap">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">field</th>
            <th scope="col">before_data</th>
            <th scope="col">after_data</th>
            <th scope="col">date</th>
        </tr>
        </thead>
        <tbody>
        {% if character_history %}
        {% for history in character_history %}
        <tr>
            <td>{{history.field}}</a></td>
            <td>{{history.before_data}}</td>
            <td>{{history.after_data}}</td>
            <td>{{history.date}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>no data</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/guild/character_list.html
{% extends 'base.html' %}
{% load guild_filter %}
{% block content %}


<h1>DAY CHART</h1>
<div class="table-responsive text-nowrap">
    <table class="table">
        <thead>
        <tr>
            <th scope="col" class="th-name">닉네임</th>
            <th scope="col" class="th-class">클래스</th>
            <th scope="col" class="th-itemlv">아이템</th>
            <th scope="col" class="th-battlelv">전투</th>
            <th scope="col" class="th-expeditionlv">원정대</th>
            <th scope="col" class="th-engraving">각인</th>
            <th scope="col" class="th-stat">특성</th>
            <th scope="col" class="th-card">카드</th>
            <th scope="col" class="th-gem">보석</th>
            <th scope="col" class="th-equipment">무기</th>
            <th scope="col" class="th-power">공격력</th>
            <th scope="col" class="th-vitality">체력</th>
            <th scope="col" class="th-date">update</th>
        </tr>
        </thead>
        <tbody>
        {% if character_list %}
        {% for character in character_list %}
        <tr>
            <td><a href="{% url 'guild:history' character.character_name%}" target="_blank">{{character.character_name}}</a></td>
            <td><p>{{character.character_class}}</p></td>
            <td><p>{{character.character_item_level}}</p></td>
            <td><p>{{character.character_battle_level}}</p></td>
            <td><p>{{character.character_expedition_level}}</p></td>
            <td>
                <p>{{character.engraving_simple}}</p>
                <div class="detail">
                    {% for engraving in character.engraving_as_list %}
                    <p>{{engraving}}</p>
                    {% endfor %}
                </div>
            </td>
            <td>
                {% for stat in character.stat_as_list %}
                <p>{{stat}}</p>
                {% endfor %}
            </td>
            <td>
                {% for card in character.card_slice %}
                <p>{{card}}</p>
                {% endfor %}
            </td>
            <td>
                {% for gem in character.gem_simple %}
                <p>{{gem}}</p>
                {% endfor %}
            </td>
            <td>
                <p>{{character.equipment_weapon_lv}}</p>
                <div class="detail">
                    {% for equipment in character.equipment_as_list %}
                    <p>{{equipment}}</p>
                    {% endfor %}
                </div>
            </td>
            <td><p>{{character.character_power}}</p></td>
            <td><p>{{character.character_vitality}}</p></td>
            <td>
                <p>{{character.elapsed_time}}</p>
                <div class="detail">
                    {% for history in character_history|get_item:character.character_name %}
                    <p class="history_title">{{history.field_trans}}</p>
                    <p>{{history.before_data}}</p>
                    <p>{{history.after_data}}</p>
                    {% endfor %}
                </div>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>no data</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/guild/index.html
{% extends 'base.html' %}
{% block content %}


<h2>index</h2>


{% endblock %}